name: Debug Workflow

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key to tmate
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.KEY_AUTH }} >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Keep job alive
        run: sleep 10h
